# Generated by Django 3.2.7 on 2024-03-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prottable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('start_date', models.DateField(max_length=150)),
                ('pdf_file', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='subconttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='workertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
