# Generated by Django 3.2.7 on 2024-03-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prottable',
            name='status',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
