# Generated by Django 3.2.7 on 2024-03-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_prottable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_assign_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.prottable')),
                ('sub_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.subconttable')),
            ],
        ),
    ]
