# Generated by Django 3.2.7 on 2024-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_pro_assign_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertable',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
