# Generated by Django 3.2.7 on 2024-03-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_workertable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_assign_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.prottable')),
                ('workers', models.ManyToManyField(to='construction.workertable')),
            ],
        ),
    ]
