# Generated by Django 3.2.7 on 2024-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_pro_assign_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_assign_worker',
            name='workers',
        ),
        migrations.AddField(
            model_name='pro_assign_worker',
            name='workers',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
