# Generated by Django 3.2.7 on 2024-03-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20240305_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_assign_worker',
            name='workers',
        ),
        migrations.AddField(
            model_name='pro_assign_worker',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='construction.subconttable'),
            preserve_default=False,
        ),
    ]
