# Generated by Django 3.2.7 on 2024-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_alter_pro_assign_worker_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='prottable',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
