# Generated by Django 3.2.7 on 2024-03-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_prottable_estimated_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.prottable')),
            ],
        ),
    ]
