# Generated by Django 3.2.7 on 2024-03-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_expenses_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(max_length=500, upload_to='')),
                ('permit_file', models.FileField(max_length=500, upload_to='')),
                ('design_file', models.FileField(max_length=500, upload_to='')),
                ('other', models.FileField(max_length=500, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.prottable')),
            ],
        ),
    ]
