# Generated by Django 3.2.7 on 2024-03-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_documents_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_wages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hour', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.prottable')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.workertable')),
            ],
        ),
    ]
